# Generated by Django 5.1.2 on 2025-05-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
